name: üê≥ Docker Compose CI

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.6
        options: --privileged

    steps:
      - name: üõéÔ∏è Checkout code
        uses: actions/checkout@v4

      - name: üê≥ Set up Docker Compose (via setup-buildx)
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "DJANGO__SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "DJANGO__DEBUG=True" >> .env
          echo "DJANGO__ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
          echo "POSTGRES_HOST=localhost" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=django_db" >> .env
          echo "SUPERUSER_USERNAME=admin" >> .env

      - name: ‚öôÔ∏è Build and run containers
        run: docker compose --profile full_dev up -d --build

      - name: ‚úÖ Run Django checks and tests
        run: |
          docker compose --profile full_dev exec app python manage.py check
          docker compose --profile full_dev exec app python manage.py test